### PR TITLE
Create de_de.json

### PR DESCRIPTION
**Pull request by Geolykt**
I wasn't able to translate the last third of the file as it contains too many Words which I do not know and even If I were to google translate them, I highly doubt it would make them any accurate as I wouldn't be able to check them afterwards.

### CODE REVIEW

**Comment by kwpugh** [comment]
Incorporated in next release.

**Comment by Geolykt** [comment]
Any reason this was reopened?

**Comment by kwpugh** [comment]
Mistake.   What is your Curseforge ID?   I was going to add you as a translator

**Comment by Geolykt** [comment]
That would be https://www.curseforge.com/members/wekabu_city

**Comment by kwpugh** [comment]
Added!  Thank you for the translation work.

**Pull request closed without merging**
