### PR TITLE
Updat zh_cn.json 1.15.2

### PR DESCRIPTION
**Pull request by Aemande123**
Updat zh_cn.json 1.15.2

In addition
Your localized text seems to be missing a key entry:
The Veggie Way 20

After you add, please notify me and I will update in sync.

### CODE REVIEW

**Comment by kwpugh** [comment]
accepted the merge request and added the new tag for Quinoa Plant

**Comment by kwpugh** [comment]
I have updated my others mods if you have interest in translating them.

Rather than PRs, it would’ve easier if you put the Lang file content into Gist and send me a link.  Then I just cut-n-paste.

**Comment by kwpugh** [comment]
My other mods: https://www.curseforge.com/members/kwpugh/projects

**Comment by Aemande123** [comment]
> My other mods: https://www.curseforge.com/members/kwpugh/projects

I am honored to translate your mods, but due to work reasons, I have recently had a hard time taking the time to do translation work. It will take a while to wait, sorryTT.
After I finish translating, I will submit it as an issue.

**Comment by kwpugh** [comment]
Great thanks.  I appreciate any help I can get.   MCBBS keeps asking to link to my mods, so sounds like there is interest in the community.

**Comment by kwpugh** [comment]
what is your Curseforge ID, so I can add your as a translator?

**Comment by Aemande123** [comment]
> what is your Curseforge ID, so I can add your as a translator?

because of GFW, I cannot register for a twitch account,so I cannot provide the curseforge ID.
I'm so sorry
You might be able to use github ID.

**Comment by kwpugh** [comment]
No problem.

**Pull request merged**
