### PR TITLE
Update zh_cn.json

### PR DESCRIPTION
**Pull request by Aemande123**

### CODE REVIEW

**Comment by kwpugh** [comment]
Manually incorporated.   No translation for "Carrot Soup"

**Comment by kwpugh** [comment]
Maybe:   胡萝卜汤

**Comment by Aemande123** [comment]
> Maybe: 胡萝卜汤

Yes! the word is 胡萝卜汤
I'm sorry I was negligent.

**Comment by kwpugh** [comment]
Thank you for all your help.   Greatly appreciated.

**Comment by Aemande123** [comment]
> Thank you for all your help. Greatly appreciated.

My pleasure.

**Pull request closed without merging**
