### PR TITLE
Dutch Localization

### PR DESCRIPTION
**Pull request by HeresHavi**

### CODE REVIEW

**Comment by kwpugh** [comment]
Will be in next release.

**Comment by kwpugh** [comment]
I added "Pumpkin Soup" to a recent version.   Translation?

**Comment by HeresHavi** [comment]
> I added "Pumpkin Soup" to a recent version. Translation?

That would be **Pompoensoep**

**Comment by kwpugh** [comment]
Push new release now.  Thank you.

**Comment by kwpugh** [comment]
Hi

I moved all of the static tool tips out of classes and into the Lang file.  Would you mind taking another pass at the translation?

Regards.

**Comment by kwpugh** [comment]
1.15.2 only.

**Comment by kwpugh** [comment]
what is your Curseforge ID, so I can add your as a translator?

**Comment by HeresHavi** [comment]
> what is your Curseforge ID, so I can add your as a translator?

That'll be
https://www.curseforge.com/members/havi

**Comment by kwpugh** [comment]
New tool tips in lang file

**Pull request closed without merging**
