### PR TITLE
Update zh_cn.json 1.15 and 1.14

### PR DESCRIPTION
**Pull request by Aemande123**
Update zh_cn.json 1.15 and 1.14，the two localization files are the same

In addition
Can I move your mods to mcbbs?
mcbbs:https://www.mcbbs.net/
mcbbs is the largest minecraft fan forum in China.

I will not provide download sources other than Curseforge

I'm sorry to ask questions here, because of GFW, I cannot register for a twitch account, so I cannot ask questions on Curseforge.

### CODE REVIEW

**Comment by kwpugh** [comment]
Thanks.  The lang updates will be included in updates.

Feel free to post on MCBS.

**Comment by Aemande123** [comment]
> Thanks. The lang updates will be included in updates.
> 
> Feel free to post on MCBS.

thank you very much！

**Comment by kwpugh** [comment]
I added more of the static tool tips from classes into the Lang file.   Would you mind taking another pass at the translations?

Regards.

**Comment by kwpugh** [comment]
1.15.2 only

**Comment by Aemande123** [comment]
> I added more of the static tool tips from classes into the Lang file. Would you mind taking another pass at the translations?
> 
> Regards.

No problem, I will translate right away.

**Pull request closed without merging**
